## File generated by the BNF Converter (bnfc 2.9.4.1).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Src/Jabba/Test

# Rules for building the parser.

Src/Jabba/Abs.hs Src/Jabba/Lex.x Src/Jabba/Par.y Src/Jabba/Print.hs Src/Jabba/Test.hs : lang/jabba.cf
	bnfc --haskell -p Src -d lang/jabba.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Src/Jabba/Test : Src/Jabba/Abs.hs Src/Jabba/Lex.hs Src/Jabba/Par.hs Src/Jabba/Print.hs Src/Jabba/Test.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f Src/Jabba/*.hi Src/Jabba/*.o Src/Jabba/*.log Src/Jabba/*.aux Src/Jabba/*.dvi

distclean : clean
	-rm -f Src/Jabba/Abs.hs Src/Jabba/Abs.hs.bak Src/Jabba/ComposOp.hs Src/Jabba/ComposOp.hs.bak Src/Jabba/Doc.txt Src/Jabba/Doc.txt.bak Src/Jabba/ErrM.hs Src/Jabba/ErrM.hs.bak Src/Jabba/Layout.hs Src/Jabba/Layout.hs.bak Src/Jabba/Lex.x Src/Jabba/Lex.x.bak Src/Jabba/Par.y Src/Jabba/Par.y.bak Src/Jabba/Print.hs Src/Jabba/Print.hs.bak Src/Jabba/Skel.hs Src/Jabba/Skel.hs.bak Src/Jabba/Test.hs Src/Jabba/Test.hs.bak Src/Jabba/XML.hs Src/Jabba/XML.hs.bak Src/Jabba/AST.agda Src/Jabba/AST.agda.bak Src/Jabba/Parser.agda Src/Jabba/Parser.agda.bak Src/Jabba/IOLib.agda Src/Jabba/IOLib.agda.bak Src/Jabba/Main.agda Src/Jabba/Main.agda.bak Src/Jabba/jabba.dtd Src/Jabba/jabba.dtd.bak Src/Jabba/Test Src/Jabba/Lex.hs Src/Jabba/Par.hs Src/Jabba/Par.info Src/Jabba/ParData.hs Makefile
	-rmdir -p Src/Jabba/

# EOF
