-- File generated by the BNF Converter (bnfc 2.9.4.1).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Src.

module Src.Jabba.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Src.Jabba.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Src.Jabba.Abs.Ident where
  prt _ (Src.Jabba.Abs.Ident i) = doc $ showString i
instance Print Src.Jabba.Abs.Program where
  prt i = \case
    Src.Jabba.Abs.PProgram instrs -> prPrec i 0 (concatD [prt 0 instrs])

instance Print Src.Jabba.Abs.Instr where
  prt i = \case
    Src.Jabba.Abs.DFun id_ args type_ block -> prPrec i 0 (concatD [doc (showString "fun"), prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString ":"), prt 0 type_, prt 0 block])
    Src.Jabba.Abs.IUnit -> prPrec i 0 (concatD [doc (showString ";")])
    Src.Jabba.Abs.IIncr id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "++"), doc (showString ";")])
    Src.Jabba.Abs.IDecr id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "--"), doc (showString ";")])
    Src.Jabba.Abs.IAss id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    Src.Jabba.Abs.IRet expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    Src.Jabba.Abs.IRetUnit -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    Src.Jabba.Abs.IYield expr -> prPrec i 0 (concatD [doc (showString "yield"), prt 0 expr, doc (showString ";")])
    Src.Jabba.Abs.IYieldUnit -> prPrec i 0 (concatD [doc (showString "yield"), doc (showString ";")])
    Src.Jabba.Abs.IIf expr block -> prPrec i 0 (concatD [doc (showString "if"), prt 0 expr, prt 0 block])
    Src.Jabba.Abs.IIfElse expr block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 expr, prt 0 block1, doc (showString "else"), prt 0 block2])
    Src.Jabba.Abs.IWhile expr block -> prPrec i 0 (concatD [doc (showString "while"), prt 0 expr, prt 0 block])
    Src.Jabba.Abs.IWhileFin expr block1 block2 -> prPrec i 0 (concatD [doc (showString "while"), prt 0 expr, prt 0 block1, doc (showString "finally"), prt 0 block2])
    Src.Jabba.Abs.IFor id_ expr1 expr2 block -> prPrec i 0 (concatD [doc (showString "for"), prt 0 id_, doc (showString "="), prt 0 expr1, doc (showString ".."), prt 0 expr2, prt 0 block])
    Src.Jabba.Abs.IForGen id_ expr block -> prPrec i 0 (concatD [doc (showString "for"), prt 0 id_, doc (showString "in"), prt 0 expr, prt 0 block])
    Src.Jabba.Abs.IExpr expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
    Src.Jabba.Abs.IDecl decl -> prPrec i 0 (concatD [prt 0 decl, doc (showString ";")])

instance Print Src.Jabba.Abs.Arg where
  prt i = \case
    Src.Jabba.Abs.RefMutArg id_ type_ -> prPrec i 0 (concatD [doc (showString "var"), prt 0 id_, doc (showString ":"), prt 0 type_])
    Src.Jabba.Abs.RefConstArg id_ type_ -> prPrec i 0 (concatD [doc (showString "val"), prt 0 id_, doc (showString ":"), prt 0 type_])
    Src.Jabba.Abs.CopyMutArg id_ type_ -> prPrec i 0 (concatD [doc (showString "var"), prt 0 id_, doc (showString ":"), doc (showString "new"), prt 0 type_])
    Src.Jabba.Abs.CopyConstArg id_ type_ -> prPrec i 0 (concatD [doc (showString "val"), prt 0 id_, doc (showString ":"), doc (showString "new"), prt 0 type_])

instance Print [Src.Jabba.Abs.Arg] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Src.Jabba.Abs.Item where
  prt i = \case
    Src.Jabba.Abs.DItemVal id_ type_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 type_, doc (showString "="), prt 0 expr])
    Src.Jabba.Abs.DItem id_ type_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 type_])

instance Print [Src.Jabba.Abs.Item] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Src.Jabba.Abs.Decl where
  prt i = \case
    Src.Jabba.Abs.DVar items -> prPrec i 0 (concatD [doc (showString "var"), prt 0 items])
    Src.Jabba.Abs.DVal items -> prPrec i 0 (concatD [doc (showString "val"), prt 0 items])

instance Print Src.Jabba.Abs.Block where
  prt i = \case
    Src.Jabba.Abs.IBlock instrs -> prPrec i 0 (concatD [doc (showString "{"), prt 0 instrs, doc (showString "}")])

instance Print [Src.Jabba.Abs.Instr] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Src.Jabba.Abs.Type where
  prt i = \case
    Src.Jabba.Abs.TInt -> prPrec i 0 (concatD [doc (showString "Integer")])
    Src.Jabba.Abs.TBool -> prPrec i 0 (concatD [doc (showString "Boolean")])
    Src.Jabba.Abs.TString -> prPrec i 0 (concatD [doc (showString "String")])
    Src.Jabba.Abs.TGen type_ -> prPrec i 0 (concatD [doc (showString "Gen"), doc (showString "["), prt 0 type_, doc (showString "]")])
    Src.Jabba.Abs.TVoid -> prPrec i 0 (concatD [doc (showString "Unit")])

instance Print Src.Jabba.Abs.PlsOp where
  prt i = \case
    Src.Jabba.Abs.OPlus -> prPrec i 0 (concatD [doc (showString "+")])
    Src.Jabba.Abs.OMinus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print Src.Jabba.Abs.MulOp where
  prt i = \case
    Src.Jabba.Abs.OMul -> prPrec i 0 (concatD [doc (showString "*")])
    Src.Jabba.Abs.ODiv -> prPrec i 0 (concatD [doc (showString "/")])
    Src.Jabba.Abs.OMod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print Src.Jabba.Abs.NotOp where
  prt i = \case
    Src.Jabba.Abs.ONot -> prPrec i 0 (concatD [doc (showString "!")])

instance Print Src.Jabba.Abs.NegOp where
  prt i = \case
    Src.Jabba.Abs.ONeg -> prPrec i 0 (concatD [doc (showString "-")])

instance Print Src.Jabba.Abs.AndOp where
  prt i = \case
    Src.Jabba.Abs.OAnd -> prPrec i 0 (concatD [doc (showString "&&")])

instance Print Src.Jabba.Abs.OrOp where
  prt i = \case
    Src.Jabba.Abs.OOr -> prPrec i 0 (concatD [doc (showString "||")])

instance Print Src.Jabba.Abs.RelOp where
  prt i = \case
    Src.Jabba.Abs.REq -> prPrec i 0 (concatD [doc (showString "==")])
    Src.Jabba.Abs.RNeq -> prPrec i 0 (concatD [doc (showString "!=")])
    Src.Jabba.Abs.RLt -> prPrec i 0 (concatD [doc (showString "<")])
    Src.Jabba.Abs.RGt -> prPrec i 0 (concatD [doc (showString ">")])
    Src.Jabba.Abs.RLeq -> prPrec i 0 (concatD [doc (showString "<=")])
    Src.Jabba.Abs.RGeq -> prPrec i 0 (concatD [doc (showString ">=")])

instance Print Src.Jabba.Abs.Expr where
  prt i = \case
    Src.Jabba.Abs.EVarName id_ -> prPrec i 6 (concatD [prt 0 id_])
    Src.Jabba.Abs.EIntLit n -> prPrec i 6 (concatD [prt 0 n])
    Src.Jabba.Abs.EBoolLitTrue -> prPrec i 6 (concatD [doc (showString "true")])
    Src.Jabba.Abs.EBoolLitFalse -> prPrec i 6 (concatD [doc (showString "false")])
    Src.Jabba.Abs.ERun id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    Src.Jabba.Abs.EStringLit str -> prPrec i 6 (concatD [printString str])
    Src.Jabba.Abs.ENeg negop expr -> prPrec i 5 (concatD [prt 0 negop, prt 6 expr])
    Src.Jabba.Abs.ENot notop expr -> prPrec i 5 (concatD [prt 0 notop, prt 6 expr])
    Src.Jabba.Abs.EMul expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    Src.Jabba.Abs.ESum expr1 plsop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 plsop, prt 4 expr2])
    Src.Jabba.Abs.ERel expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    Src.Jabba.Abs.EBAnd expr1 andop expr2 -> prPrec i 1 (concatD [prt 2 expr1, prt 0 andop, prt 1 expr2])
    Src.Jabba.Abs.EBOr expr1 orop expr2 -> prPrec i 0 (concatD [prt 1 expr1, prt 0 orop, prt 0 expr2])
    Src.Jabba.Abs.ETer expr1 expr2 expr3 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "?"), prt 1 expr2, doc (showString ":"), prt 0 expr3])

instance Print [Src.Jabba.Abs.Expr] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]
